### ISSUE TITLE
start new f7-reakt template project

### ISSUE THREAD

**Issue by agreif** [bencompton/framework7-react#14]
Hi,
thanks for this project, and I really want to begin working with it, but
could somebody please provide a small bootstrap command sequence to create a new f7-react project, so that it can be extended?
Sure, I could take the kitchensink and then tailor it for my needs, but I would prefer a new clean project to start with.
Thanks.

**Comment by bencompton** [comment]
@agreif, here's a brand new starter template that was just released today. See what you think:

https://github.com/bencompton/framework7-react-app-template

**Comment by agreif** [comment]
thanks a lot!!
