### ISSUE TITLE
Cannot find module '../Framework7'

### ISSUE THREAD

**Issue by bvodola** [bencompton/framework7-react#19]
When I was trying to run the project, the following message showed in the browser console:

``Cannot find module '../Framework7'``

Also, the following showed in the terminal:

```
  "../Framework7" in
/home/bvodola/Projects/meteor-react-f7-skel/node_modules/framework7-react/dist/src/utils/ReactifyF7Vue.js
(web.browser)
  "../src/Framework7" in
/home/bvodola/Projects/meteor-react-f7-skel/node_modules/framework7-react/dist/framework7-react/index.js
(web.browser)
```

I checked the framework7-react inside node_modules and realized that some files were trying to import Framework7.js with a capital **F**, whereas the module path was:

``node_modules/framework7-react/dist/src/framework7.js``

with a small **f**. I renamed it as capital and everything works great now.

**Comment by bencompton** [comment]
Thanks for the detailed issue report. This should be fixed in the latest version (0.8.5-beta.3).
