### ISSUE TITLE
Static lib is not AMD

### ISSUE THREAD

**Issue by thiagoabreu** [bencompton/framework7-react#21]
Hi. I had a little trouble on using this lib with Apache Cordova.

You see, as Cordova is mostly a webbrowser, it cannot work with CommonJS modules, only AMD. 

The way I find to make this work was compiling the lib with the following webpack config: 

```javascript
output: {
            filename: 'framework7-react.js',
            library: 'framework7-react',
            libraryTarget: 'amd'
        },    
```
instead of:

```javascript
output: {
            filename: 'framework7-react.js',
            library: 'Framework7React',
            libraryTarget: 'var'
        },    
```

This way I'm able to use this lib without the need of Webpack in my application.

Is that the recomended way?

**Comment by bencompton** [comment]
There is actually a [static template](https://github.com/bencompton/framework7-react-static-template) available that does not require Webpack, but unless your app is pretty small, I would recommend using the [Create React App template](https://github.com/bencompton/framework7-react-app-template) with Cordova instead. That way, you can use ES6 + JSX and have your final build compile to a single minified .js file for deployment. It is on my list of things to do to create a Cordova template that leverages Create React App, but I haven't gotten around to it yet.

If you haven't used Create React App yet, it has the benefit of being simpler to use than Webpack (while using Webpack behind the scenes and providing the option to "eject" to a custom Webpack configuration).

**Comment by thiagoabreu** [comment]
That's ok. The project I'm working right now is just a initial prototype.

I created this issue because the Tools for Apache Cordova for Visual Studio doesn't natively support webpack... Well... It does, but right now we need the code/build/test process fast. 

Anyway. Thanks for the tips. I'll use the create-react-app when the real implementation starts.

**Comment by bencompton** [comment]
The static build now has UMD instead of AMD, so that should now accommodate future use cases like this.
