### ISSUE TITLE
App Initialized Instances

### ISSUE THREAD

**Issue by bvodola** [bencompton/framework7-react#22]
I've been struggling with finding a way to get the same initialized instances we have in Vue.js to react, when we initialize the app:
http://framework7.io/vue/init-app.html#initialized-instances

Following your example, I could find the theme instance only, through `context.framework7AppContext.theme`. But what about the others? Could you point me out a way? Thanks!

**Comment by bencompton** [comment]
Vue instance properties are a pretty nice, but React doesn't really have an equivalent standard other than context, which is not quite as convenient. The docs for F7 React are going up very soon, but until then, here is what is available in context.framework7AppContext:

|Name|Description|
| --- | --- |
| theme | Has two boolean properties: ios and material. Depending on the themeType prop passed into Framework7App ("ios" or "material"), the respective ios or material property will be true and the other will be false.|
|routes|Routes passed into Framework7App|
|.getCurrentRoute()|Get the currently active route|
|.getRouter()|Get the Framework7 React router|
|.getFramework7()| Get Framework7App's internal instance of Framework7|

In addition to using context, it is also possible to get access to the Framework7 instance and the current route by exporting them the module that contains your Framework7App declaration. See the kitchen sink [App.tsx](https://github.com/bencompton/framework7-react/blob/master/kitchen-sink/components/App.tsx) for more detail.

Also, I'm not entirely satisfied with either of these methods, and would certainly be interested in hearing other ideas.

**Comment by bencompton** [comment]
[Official docs](http://framework7.io/react/) are now available, so I am going to close this issue.
