### ISSUE TITLE
Links between views?

### ISSUE THREAD

**Issue by jh3141** [bencompton/framework7-react#23]
I'm struggling to get links between views to work.  I have a structure that simplifies to this:

    class TestPage extends Component
    {
      render () {
        return <Page><ContentBlock inner><p>Test page</p></ContentBlock></Page>;
      }
    }
    let routes = [
      { path: "/moreInfo", component: TestPage }
    ];

    ...
    <Framework7App routes={routes}>
       <Panel opened={true} left>
           <View><Pages><Page>
               <ContentBlock inner><Link view="#main-view" href="/moreInfo">More info</Link></ContentBlock>
           </Page></Pages></View>
       </Panel>
       <Views><View main id="main-view">
            <ContentBlock inner><p>Default content</p></ContentBlock>
       </View></Views>
     </Framework7App>

If I remove the `view="#main-view"` section, then the TestPage component replaces the content of the left panel as expected.  But with the view specified, I get the following error:

    TypeError: undefined is not an object (evaluating 'self.$parent.f7View').  

The error occurs in the method "VuePages.methods.onRouteChange" exported from the module "framework7-vue.js".

**Comment by jh3141** [comment]
Single stepping through the method, it seems that it is called twice when the link is clicked.  The first time it completes successfully, but the second time `$parent` evaluates to `undefined` causing the error.

**Comment by bencompton** [comment]
It looks like you just forgot the `Pages` and `Page` components in your main view. As you can see, it works in [this fiddle](https://jsfiddle.net/vkqwe6k0/8/). Instead of the `view` prop on your link, you can also use `linkView` as [this fiddle](https://jsfiddle.net/vkqwe6k0/6/) shows, which will close the panel when you click the link.
