### ISSUE TITLE
Back icon and Menu icon overlapping in RTL direction

### ISSUE THREAD

**Issue by GROL** [bencompton/framework7-react#27]
Hi,
I see a React template from your repository https://github.com/bencompton/framework7-react-app-template and I uses RTL stile 
```
import 'framework7/dist/css/framework7.material.rtl.min.css';
```

When I click the navigation item About or Form I see icons and title overlapping 
![tittle](https://cloud.githubusercontent.com/assets/1935343/24745123/1ae7c162-1abd-11e7-9367-81c39bee7fa7.jpg)

Can you fix it?

**Comment by bencompton** [comment]
Hello, sorry for not getting back to you sooner. Maybe you already figured it out by now, but It looks like you just need to set the theme to "iOS" in your Framework7App component:

```javascript
<Framework7App themeType="material" routes={routes}>
```
