### ISSUE TITLE
`SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag` error when running `gulp` command

### ISSUE THREAD

**Issue by achmadk** [bencompton/framework7-react#30]
Excuse me, @bencompton. I have tried to build this package in my local notebook. I have installed all dependencies using `npm i`, then run `gulp` command. Unfortunately, I got error like this in command prompt window 

```
I:\[OUTSIDE PROJECTS]\framework7-react>gulp
[22:36:32] Requiring external module babel-register
[22:36:34] Using gulpfile I:\[OUTSIDE PROJECTS]\framework7-react\gulpfile.babel.js
[22:36:35] Starting 'clean'...
[22:36:35] Finished 'clean' after 40 ms
[22:36:35] Starting 'build-framework7-core'...
[22:36:35] Starting 'compile-framework7-vue'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (6:0)
2 :   <div class="accordion-item-content">
3 :     <slot></slot>
4 :   </div>
5 : </template>
6 : <script>
    ^
    at error (I:\[OUTSIDE PROJECTS]\framework7-react\node_modules\rollup\src\utils\error.js:2:14)
    at I:\[OUTSIDE PROJECTS]\framework7-react\node_modules\rollup\src\utils\transform.js:95:6
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
Is there any solution to solve this problem?

**Comment by bencompton** [comment]
That's a really strange error--it looks like the Vue code compilation is interpreting the .vue file as React JSX for some reason. I'm not exactly sure how that would happen. I just did a fresh clone in macOS, `npm install`, and `gulp`, and it worked fine. Then I did a fresh clone on Windows like it appears you're using and it worked fine too (used Cmd shell).

The only thing I see that looks off is that the directory "OUTSIDE PROJECTS" you're using has a space in it. Seems unlikely, but that may be messing something up.

**Comment by achmadk** [comment]
Thanks for your solution @bencompton

First, I rename `[OUTSIDE PROJECTS]` to `[OUTSIDE_PROJECTS]` (replace space to `_`) according to your solution, but still show same error. Finally, `gulp` command successfully executed after I rename my folder to `OUTSIDE_PROJECTS` (without `[]`).

**Comment by bencompton** [comment]
Ah, glad it was that simple. Nice work narrowing it down to the brackets.
