### ISSUE TITLE
Can't open another pages in kitchen sink when `framework7-vue` is updated to version 0.9.0

### ISSUE THREAD

**Issue by achmadk** [bencompton/framework7-react#31]
Excuse me, @bencompton . Finally I can know what's actually changed between framework7-vue v0.8.5 and v0.9.0. You can view it [in this link](https://github.com/nolimits4web/Framework7-Vue/compare/master@%7B2017-03-02%7D...master@%7B2017-04-11%7D). Variable names for handling router has been changed in `pages.vue` and also in `framework7-vue.js`, so I can just view the main page, can't open others page like chips, data table, dynamic routing, etc, when open kitchen sink. I hope that link can help you to update `framework7-react` package to newer version.

**Comment by bencompton** [comment]
Thanks for all of the investigation you have done. I am hoping to have more time to get the v0.9 release  out soon.

**Comment by bencompton** [comment]
Should be fixed now in v0.9.1.
