### ISSUE TITLE
React.createClass is deprecated warning

### ISSUE THREAD

**Issue by smshuja** [bencompton/framework7-react#32]
I am getting this warning with React 15.5.4

`Warning: F7AccordionContent: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

**Comment by bencompton** [comment]
Thanks for the issue report. This issue will hopefully be an easy fix, and should be fixed in the next version.

**Comment by smshuja** [comment]
Thanks @bencompton there is also another warning about deprecated PropTypes, these were deprecated recently, will file that as a separate issue.

**Comment by bencompton** [comment]
Should be fixed now in v0.9.1.
