### ISSUE TITLE
FormInput events like onOnkeypress, onKeyup, onKeydown don't work

### ISSUE THREAD

**Issue by smshuja** [bencompton/framework7-react#33]
None of the input events seem to work except `onChange`

This doesn't work.

`<FormInput type="text" placeholder="Name" onKeyup={(e) => console.log(e)} />`

I am trying to prevents the form from being submitted and also need to prevent certain characters being typed in the field.

**Comment by bencompton** [comment]
Thanks. The keyup event is not currently implemented, but I agree that it should be.

**Comment by smshuja** [comment]
@bencompton Where should I be looking to implement this. Been reading the code but couldn't figure out where these events are getting dropped. I tried adding onKeyUp and onKeyDown to ManagedFormInput.tsx and these show up in the React dev tools but the handlers are not called.

If you can point me in the right directly I would be happy to send a PR.

**Comment by bencompton** [comment]
Hey, thanks,, that would definitely be appreciated! 

When the Vue FormInput component attempts to create an input element, Framework7 React basically intercepts that and instead creates the [ManagedFormInput](https://github.com/bencompton/framework7-react/blob/master/src/components/inputs/ManagedFormInput.tsx) in Framework7 React. That component is there to get around React's controlled / uncontrolled input issues.

What that component fails to do currently is to implement all of the events that the [FormInput](https://github.com/nolimits4web/Framework7-Vue/blob/master/src/components/form-input.vue#L35) Vue component needs.

I think that all that needs to be done is to add those events that the Vue code there has, and it should work. I really hope that's all it will take at least.

**Comment by bencompton** [comment]
Should be fixed now in v0.9.1.
