### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by smshuja** [bencompton/framework7-react#45]
I get this warning.

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by bencompton** [comment]
All of the warnings in React 15.5 will be fixed in the 0.9.1 release, which I'm hoping to get out in the next week or so.

**Comment by bencompton** [comment]
Should be fixed now in v0.9.1.
