### ISSUE TITLE
[React] Custom labels for confirm/alert/prompt buttons.

### ISSUE THREAD

**Issue by renatoholanda** [bencompton/framework7-react#47]
Please, custom labels for buttons "cancel", "ok".

**Comment by bencompton** [comment]
In framework7-react, you call the Framework7 API (or framework7-redux API) to show modals. In the Framework7 API, the confirm, alert, and prompts are just shortcuts to the `modal` method, and if you need anything customized, that's the method you will want to call: http://framework7.io/docs/modal.html#custom-modals.

Does that address what you would like to accomplish?

**Comment by renatoholanda** [comment]
Wow! Yeah, @bencompton. Thanks!
