### ISSUE TITLE
Autocomplete with framework7-react?

### ISSUE THREAD

**Issue by kobyl** [bencompton/framework7-react#49]
Hello,

  Just wondering if autocomplete can be used with f7-react? I tried wiring into the onFramework7Init callback and I see it fire, but it seems that it's already too late to do the page init stuff?

https://jsfiddle.net/oopgxfnh/2/

Thanks!

**Comment by bencompton** [comment]
Looks like a timing issue. You should have better luck with the `componentDidMount` event instead of the `onPageInit` event:

https://jsfiddle.net/oopgxfnh/3/

**Comment by kobyl** [comment]
Thanks!
