### ISSUE TITLE
Name on FormInput

### ISSUE THREAD

**Issue by renatoholanda** [bencompton/framework7-react#50]
I have this code

`<FormInput type="password" id="signup_password" name="signup_password" placeholder="Senha" />`

But on generated HTML doesn't show the **name** attr.

`<input type="password" placeholder="Senha">`

Is it a bug?

**Comment by bencompton** [comment]
This is a bug that is related to #33. Framework7 React intercepts the FormInput, but neglects to pass on all of its potential properties and events.

**Comment by renatoholanda** [comment]
Thanks, Ben. I'm waiting for next release 😃

**Comment by bencompton** [comment]
Should be fixed now in v0.9.1.

**Comment by devel-pa** [comment]
Name works, cannot set value ;(

**Comment by bencompton** [comment]
Try version 0.9.2.

**Comment by devel-pa** [comment]
@bencompton Probably I should open another issue. FormInput (switch) value and checked is not set.
