### ISSUE TITLE
Virtual list items events and others

### ISSUE THREAD

**Issue by devel-pa** [bencompton/framework7-react#53]
Hi, 
I'm trying to do some stuff and I have no result in the last week.

As for Vue side looks like there is a solution found at https://github.com/nolimits4web/Framework7-Vue/issues/8

For React stuff I'm not finding any.

```
         <List className="searchbar-found" id="search-list" ref="found"
             style={{display: this.state.found ? 'block' : 'none' }}
            virtual form
            virtualItems={this.state.items}
            onChange={ this.onRadioSelected }
            >
            <Template7Template>
              <ListItem radio name="fromRadio"
                title={"{{name}}, {{country}}"}
                value={"{{name}}, {{country}}"}
                onChange={ this.onRadioSelected }
                 />
            </Template7Template>
            </List>
```
I found no way to get  trigger an event like `onChange`  or to update the component state.

Could be a bug? Could be a usecase that is handled easily in Vue and should be treated differently in React? Or is some knowledge I'm missing, as I'm not finding how to do such event delegation in React.

I have to mention that the functionality I'm trying to replicate is like a Smart Select opened from the beginning searching items from server, none at the beginning, 

I have to mention that neither the value is set, remaining "on", pretty useless.

Thank you very much,
Paul

**Comment by bencompton** [comment]
What is happening in the `Template7Template` is a bit deceptive. You are passing in a list item, which React renders, but the HTML of your list item ends up being a template that gets fed into Template7. The reason event handlers don't work is because React is not rendering your list items, Template7 is.

Therefore, in order to add an event handler to individual list items, it is not possible to do that with React, since React didn't render them. Instead, it is necessary to add event handlers via the DOM, as the Vue example you pointed out is doing.

In your Vue example, it suggested handling the event in the `mounted` event, which equates to the React `componentDidMount` event. Unlike Vue, React doesn't provide easy access to rendered elements via `this.el`, so you'll also have to use the refs functionality in React to get access to that.

**Comment by devel-pa** [comment]
Thank you very much for your answer. I'll try to find a different way to build that.

`Template7Template` neither makes a template as a template. In my opinion it shouldn't have any opinionated choice of the attributes set in the template.

As the list is dynamic I found no way to handle it in `componentDidMount`, but I'll study more.

**Comment by nolimits4web** [comment]
Or (if you use recent version of F7) there is a `renderExternal` VL option that allows to pass rendering to Vue/React. Here is an example https://github.com/nolimits4web/Framework7-Vue/blob/master/kitchen-sink/pages/virtual-list-vue.vue

**Comment by bencompton** [comment]
Yes, that seems like a much better way to handle virtual lists!

framework7-react is currently on framework7-vue version 9.1, so it currently doesn't have the new virtual list capabilities introduced in 0.9.2. I'll see about putting out version 0.9.2 of framework7-react. It doesn't appear that much has changed that could break anything.

**Comment by nolimits4web** [comment]
By the way, it is good performance test, will be interesting to see how React rendering here is compared to vanilla t7 virtual list. When rendering it with Vue it works significant slower than vanilla version but still acceptable

**Comment by devel-pa** [comment]
f7-react 0.9.1 I was unable to use virtual list as you said.
Instead:

```
          <List className="searchbar-found" id="search-list" ref="found"
             style={{display: this.state.found ? 'block' : 'none' }}
             form
            >
              {this.state.items.map((item, index) => {
                let value = `${item.name}, ${item.country}`;

                this.rerender = true;
                return <ListItem radio name="fromRadio" key={value}
                  title={value}
                  checked={value === this.state.selected }
                  value={value}
                  onChange={ (e) => this.onRadioSelected(e, value) }
                 />
               })}
            </List>
```

Renders the stuff but:
- value="on"
- onChange fires twice
- every time I'm changing the state whiole list is rerendered (my issue)

**Comment by bencompton** [comment]
Version 0.9.2 is now available with the new 'renderExternal' option. See the kitchen sink for example usage:

https://github.com/bencompton/framework7-react/blob/master/kitchen-sink/components/pages/VirtualListReactPage.tsx

**Comment by devel-pa** [comment]
Thanks, I upgraded, but I'll check after I'll fix some other issue, like FormInput missing checked and value.
