### ISSUE TITLE
import module in Typescript

### ISSUE THREAD

**Issue by 2857** [bencompton/framework7-react#55]
Trying to import module in ts,
```
import { Page } from "framework7-react";
```

 and gotta the below result

```
Uncaught TypeError: Cannot read property 'getFramework7' of undefined
```

seemingly the bug is located in the reactifyvuef7 file, 
```
  framework7AppContext.getFramework7(function (f7) {
         _this.framework7 = f7;
  });
```

also a newer to typescript, looks like I failed to import Page

**Comment by thiagoabreu** [comment]
I had a similar problem, and I found it occurs in two cases:

1- When contextTypes is not declared.

You must declare the contextType of every single component you need to use the context, or it'll be undefined. Some thing like this (it's in TypeScript):

```ts
const MainViews = (props:any, context: any) => (<Views> ... </Views>)

//...

(MainViews as any).contextTypes = {
    framework7AppContext: React.PropTypes.object
};
```

2- When you call before the Framework7 initiates

It takes some time for the Framework7 to init, and that could happen AFTER the React components are rendered. So you may need to have a default behavior without it while it is loading.

Hope that could help.
