### ISSUE TITLE
Checkbox onChange firing twice

### ISSUE THREAD

**Issue by kobyl** [bencompton/framework7-react#58]
Hello,

  Looks like the ListItem checkbox onChange event is firing twice.

https://jsfiddle.net/bs68kzg6/

Open up the console to see the two events.

BTW - what's the best practice to get the current state of the checkbox? It doesn't look like the kitchen sink demo has any reference to checkboxes at all. :(

Thx!

**Comment by kobyl** [comment]
BTW - changed over to raw framework7 and it doesn't seem to be happening. It's causing a problem for me because the checkbox seems to get fired with '' in my app, which is causing me to incorrectly update state.

**Comment by rvknt088** [comment]
Guys any update for issue #58. I am also getting this.
