### ISSUE TITLE
what about testing

### ISSUE THREAD

**Issue by anuragnagarkota** [bencompton/framework7-react#62]
Hey Ben!

How to perform testing using jest?

**Comment by kobyl** [comment]
Hi there,

  Just use snapshot testing per Jest instructions. There's nothing special about these react components.

Koby

**Comment by anuragnagarkota** [comment]
Hey Koby!
Thanks for the reply. Actually am using jest, but problem is that when I mount a component then it throws an error "cannot read property getFramework7 of undefined." If I use shallow then it works fine. Please help to solve this.

**Comment by kobyl** [comment]
Ah - ok. I ran into the same thing. Are you wrapping your test components  <Framework7App/>? If not, I think they'll throw that error.

**Comment by anuragnagarkota** [comment]
Thanks a lot Koby! It worked...
