### ISSUE TITLE
NavBar onBackClick event not working

### ISSUE THREAD

**Issue by adburlacu** [bencompton/framework7-react#70]
Im trying to trigger the onBackClick event of the NavBar and it's not working. 
Documentation: Navbar Events: onBackClick | Event will be triggered when click on navbar back link

`<Navbar backLink=“Back” onBackClick={ () => {this.myFunction}} title=“My page” sliding />`

Note that the backLink is working as expecting, but myFunction is never called.

**Comment by jascolley** [comment]
Did you try changing your code to { () => { this.myFunction(); } } ?

**Comment by adburlacu** [comment]
@jascolley 
Yes, i tried your suggestion `<Navbar backLink=“Back” onBackClick={ () => {this.myFunction()}} title=“My page” sliding />` and the function is still not triggerting.

Part of the code, also tried other approaches for myFunction:

```
class MyClass extends React.Component {

  constructor(props, context) {
    super(props, context);

    this.myFunction = this.myFunction.bind(this);
  }

  myFunction() {
    console.log("Jon Doe");
  }

render() {
    return (
      <Page>
        <Navbar
          backLink="Back"
          onBackClick={this.myFunction}
          title="My Title"
          sliding />
         /* Some List component with ListItems...*/
      </Page>
    );
  }
```

Any other suggestions? Is the onBackClick event not working for the NavBar or i just use it badly?

**Comment by adburlacu** [comment]
I was using v0.9.2 (that was the last version on npm yesterday), i updated to v0.9.3 and now the onBackClick event it's working. Thanks and keep up the good work on Framework7! 👍
