### ISSUE TITLE
Cannot build kitchen-sink

### ISSUE THREAD

**Issue by rossmartin** [bencompton/framework7-react#74]
I'm trying to see if I can reproduce issue #73 in the kitchen-sink but I cannot get it to build.

I was able to build the framework itself after fixing some keys in the `rollup` function in `framework7-vue-build.js`.  I had to change `moduleName` to `name`, `useStrict` to `strict`, and `sourceMap` to `source` -

Before:
![image](https://user-images.githubusercontent.com/2498502/31729636-34aa8c98-b3f5-11e7-8870-a2d1eebe340a.png)

After:
![image](https://user-images.githubusercontent.com/2498502/31729625-28962aa2-b3f5-11e7-92a3-b174b4ccedb2.png)

Once I fixed those options I could build the framework but when I try to build the kitchen-sink I see tons of TypeScript errors - 

![image](https://user-images.githubusercontent.com/2498502/31729850-deec9f48-b3f5-11e7-8ce0-fbd383f3fa33.png)

I tried to build the kitchen-sink using `typescript` `@2.3.4` and `@2.5.3` - the `package.json` in the kitchen-sink has `^2.3.4` and you end up getting `2.5.3` so I tried explicitly grabbing `2.3.4` to see if it would work and it doesn't.

Thank you for the work on this I am very likely going to be using this for a new project.

**Comment by bencompton** [comment]
Sorry, the docs are a bit out of date. The project actually uses Yarn instead of NPM, so please try doing `yarn install` instead of `npm install`. That should address the TypeScript errors.
