### ISSUE TITLE
Huge time to evaluate Framework7 scripts

### ISSUE THREAD

**Issue by dorianrod** [bencompton/framework7-react#80]
Hi,
I've noticed that framework7 react library takes a huge time to be evaluated, slowing the whole page.

When i look the console performance:
- without F7 (just react) - 2200ms to evaluate script and 412ms to compile
- with F7 and react - 660ms to evaluate and and 350 to compile

here are some captures of the console:
- with F7 : https://ibb.co/iXqdxm
- without F7 : https://ibb.co/fEhBiR

Is there a way to improve this performance ? for example, can i charge only modules i need ?

**Comment by bencompton** [comment]
Hello,

Thanks for taking the time to put together this info. I tested on an old 2010 MacBook and was able to reproduce the 2s script evaluation time by pulling down the latest and running the Kitchen Sink. When the KS is compiled with the Webpack UglifyJsPlugin, that does take the total evaluation time down to 1s. 

It certainly isn't ideal that there is such a large amount of JS to evaluate, but with Framework7 1.x and its lack of ES modules, tree shaking is not an option. Framework7 2.0 was rewritten to take advantage of ES modules, and therefore tree shaking should be possible. Once Framework7 React supports F7 v2, it will be possible to include only components your app is actually using. I can't promise any timeframes for V2 at the moment, but it is in the plans.

For the time being, minifying is an easy step to take. If startup time is critical, server rendering and shipping down the initial app data (to avoid waiting until the scripts evaluate before even requesting the data) would likely help in many cases.
